### ISSUE TITLE
Dronin Altitude incorrect + no Speed

### ISSUE THREAD

**Issue by cpusmith** [ShikOfTheRa/scarab-osd#245] opened 2016-05-23 17:21 UTC
I'm not sure if I have MWOSD configured incorrectly or not but the Speed indicator always reads zero and the default Altitude reads -21 meters although it's pretty accurate in incrementing (-19 at 2 meters of height). I've added the GPS Altitude and it appears to start at 0 and increments but is not as accurate as the barometer Altitude which I'd prefer to use.

I'm using a Sparky 1.1 on a 250 frame with MWOSD 1.6 Master on a Micro MinimOSD and dRonin 2016-04-09.2 Release ("Tanto")

#234

**Comment by tracernz** [comment] 2016-05-23 18:49
We send the wrong altitude by the looks. It needs to be inverted in the case where it comes from PositionActual.Down (PositionActual uses the NED co-ordinate system). https://github.com/d-ronin/dRonin/blob/next/flight/Modules/UAVOMSPBridge/UAVOMSPBridge.c#L461

**Comment by ShikOfTheRa** [comment] 2016-05-26 12:07
Thanks tracernz. Doesn't sound like anything for MWOSD. 

Can someone advise if / when a patch is made available in dRonin

**Comment by dustin** [comment] 2016-05-26 12:08
You can just close this bug.  It's a dRonin thing.  I thought it had been
fixed over there, but not sure if it's come out in a release.

**Comment by tracernz** [comment] 2016-06-02 07:39
Issue raised to fix this.

**Comment by ShikOfTheRa** [comment] 2016-06-02 08:50
Re-opened to keep track

**Comment by cpusmith** [comment] 2016-06-02 18:48
Will you also be looking at the zero speed display as well?

**Comment by tracernz** [comment] 2016-06-02 18:51
Can do, on brief inspection looks like the only place we send a speed through is the raw GPS message.

**Comment by tracernz** [comment] 2016-06-14 01:55
@cpusmith Can you please test d-ronin/dRonin#1035 and see if it fixes your issues? Thanks in advance.

**Comment by cpusmith** [comment] 2016-06-15 16:40
Thanks.  Will do.

**Comment by tracernz** [comment] 2016-06-24 22:02
Confirmed fixed by @cpusmith. 👍

**Comment by ShikOfTheRa** [comment] 2016-07-21 11:06
Brill

**Closed by ShikOfTheRa** 2016-07-21 11:06 UTC
