### ISSUE TITLE
Current indicator is not working witn cc3d inav and minim osd

### ISSUE THREAD

**Issue by retif** [ShikOfTheRa/scarab-osd#438] opened 2017-06-22 20:52 UTC
Using cc3d with iNAV 1.6.1. And micro minim osd with mw osd 1.7.

If autopilot is attached - current indicator is zero all the time. 
If autopilot deattached - current indicator works as expected.

**Comment by ShikOfTheRa** [comment] 2017-06-23 08:04
Where is current connector connected?  To FC or to OSD direct.
And on GUI Amperage tab can you paste a screenshot in here?

**Comment by retif** [comment] 2017-06-23 08:37
![img_20170623_113505](https://user-images.githubusercontent.com/524468/27473575-4d4430c2-5808-11e7-828d-c161b85f3b78.jpg)

Current connector connected direct to osd

**Comment by ShikOfTheRa** [comment] 2017-06-23 12:08
Ill have to replicate and test this. Will be next week unfortunately as away until then.

**Comment by ShikOfTheRa** [comment] 2017-06-27 12:37
I tried with inav and naze controller.
Seems to work OK for me.

Note – if disconnected, the amperage pin input will “float”. 
As you are seeing a voltage with it disconnected that indicates that firmware is working.

Is it possible to connect a voltmeter to the OSD current sensor input so see if any voltage being registered? Should see it rise as apply throttle

**Comment by ShikOfTheRa** [comment] 2017-06-29 21:35
Mmm might be an issue. A different setup to yours but running current through FC was not displaying on OSD.

**Comment by ShikOfTheRa** [comment] 2017-07-11 12:23
I have been away, but I can say I seem to replicate issue in plane.

**Comment by ShikOfTheRa** [comment] 2017-07-11 12:36
I hope to test and verify tonight.

**Comment by ShikOfTheRa** [comment] 2017-07-11 18:04
Fixed in main repository. 
It occurs if only use FC amperage. If use FC volts or FC RSSI it works OK. I think from memory it was by design assumed if using FC amperage you would always use volts.

**Closed** 2017-07-24 11:51 UTC
